name: Auto Gmail Creator Workflow

on:
  push:
    paths:
      - '**' # Observa todas as alterações no repositório
  pull_request:
    paths:
      - '**' # Observa todas as alterações no repositório

jobs:
  create-gmail-accounts:
    runs-on: ubuntu-latest

    steps:
      # Passo 1: Fazer checkout do repositório
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Passo 2: Configurar Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Passo 3: Instalar as dependências
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Passo 4: Baixar Chromedriver
      - name: Download Chromedriver
        run: |
          # Link direto para o Chromedriver Linux
          CHROMEDRIVER_URL="https://www.googleapis.com/download/storage/v1/b/chromium-browser-snapshots/o/Linux_x64%2F1430882%2Fchromedriver_linux64.zip?generation=1741707897235559&alt=media"
          echo "Downloading Chromedriver from: $CHROMEDRIVER_URL"

          # Baixar e configurar o Chromedriver
          wget "$CHROMEDRIVER_URL" -O chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver_linux64/chromedriver /usr/local/bin/
          chmod +x /usr/local/bin/chromedriver

      # Passo 5: Executar o script
      - name: Run Gmail Creator Script
        run: |
          python auto_gmail_creator.py
