name: Auto Gmail Creator Workflow

on:
  push:
    paths:
      - '**' # Observa todas as alterações no repositório
  pull_request:
    paths:
      - '**' # Observa todas as alterações no repositório

jobs:
  create-gmail-accounts:
    runs-on: ubuntu-latest

    steps:
      # Passo 1: Fazer checkout do repositório
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Passo 2: Configurar Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Passo 3: Instalar as dependências
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Passo 4: Baixar Chromedriver
      - name: Download Chromedriver
        run: |
          # Detectar a versão principal do Chrome
          CHROME_VERSION=$(google-chrome --version | awk '{print $3}' | cut -d '.' -f 1-3)
          echo "Detected Chrome version: $CHROME_VERSION"

          # Obter a versão mais recente do Chromedriver para a versão principal do Chrome
          CHROMEDRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION")
          echo "Downloading Chromedriver version: $CHROMEDRIVER_VERSION"

          # Baixar e configurar o Chromedriver
          wget "https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip"
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/
          chmod +x /usr/local/bin/chromedriver

      # Passo 5: Executar o script
      - name: Run Gmail Creator Script
        run: |
          python auto_gmail_creator.py
